[settings]
experimental = true
yes = true
lockfile = true

[tools]
erlang = "{{ get_env(name = 'ERLANG_VERSION', default='28.1.1') }}"
elixir = "{{ get_env(name = 'ELIXIR_VERSION', default= '1.19.1') }}"
protoc = "latest"
# "aqua:nushell/nushell" = "latest"

[env]
ELIXIR_VERSION = "1.19.1"
ERLANG_VERSION = "28.1.1"
ELIXIR_PROTOBUF_VERSION = "0.15.0"
GOOGLE_PROTOS_DIR = "googlepais"
