[settings]
experimental = true
yes = true
lockfile = true

[tools]
erlang = "{{ get_env(name = 'ERLANG_VERSION', default='28.1.1') }}"
elixir = "{{ get_env(name = 'ELIXIR_VERSION', default= '1.19.1') }}"
go = "{{ get_env(name = 'GO_VERSION', default= '1.24.6') }}"

"aqua:nushell/nushell" = "latest"
"buf" = "latest"
"go:google.golang.org/grpc/cmd/protoc-gen-go-grpc" = "latest"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "latest"
"protoc-gen-connect-go" = "latest"
protoc = "latest"

[env]
ELIXIR_VERSION = "1.19.1"
ERLANG_VERSION = "28.1.1"
GO_VERSION = "1.24.6"
ELIXIR_PROTOBUF_VERSION = "0.15.0"

[tasks.gen]
depends = ["install:elixir-proto-plugin"] 
run = [
"""
#! /usr/bin/env nu
buf generate
""",
{task = "gen:packages"}
]
